server:
  port: 11001
spring:
  application:
    name: record-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itrip_purchaserecord_db
    username: root
    password: ok
  redis:
    host: 127.0.0.1
    port: 6379
    password: ok
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:6001/eureka/
mybatis:
  config-location: classpath:mybatis-config.xml