server:
  port: 9001
spring:
  application:
    name: trip-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alx
    username: root
    password: ok
  redis:
    host: 127.0.0.1
    password: ok
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:6001/eureka/
mybatis:
  config-location: classpath:mybatis-config.xml