server:
  port: 8001
spring:
  application:
    name: user-consumer
  redis:
    port: 6379
    host: 127.0.0.1
    password: ok
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:6001/eureka/