server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:6001/eureka/
    fetch-registry: false
    register-with-eureka: false
security:
  basic:
    enabled: true
  user:
    name: root
    password: ok